#!/bin/sh
set -e

if [ $# -eq 0 ]; then
  echo "Usage: $0 [--dvr] <version>"
  exit 1
fi

if [ "$1" = "--dvr" ]; then
  cd /mnt/data
  curl -s https://getchannels.com/dvr/setup.sh | sudo -u channels env DOWNLOAD_ONLY=1 DVR_VERSION="$2" sh

  echo
  echo 'Please restart the DVR server using `systemctl restart channels-dvr`'
  exit 0
fi

version=$1
mkdir -p /mnt/data/updates
cd /mnt/data/updates
rm -f ChannelsDVRServer_PI4.raucb
wget https://channels-distro.s3.amazonaws.com/$version/ChannelsDVRServer_PI4.raucb
rauc install ChannelsDVRServer_PI4.raucb

echo
echo "Update v$version installed!"
echo 'Please reboot using `systemctl reboot`'
