#!/bin/sh
# shellcheck disable=SC2039
# ==============================================================================
# DVROS partition expander
# ==============================================================================
set -e

DEVICE_CHILD="$(findfs UUID="78eeef04-2a71-490b-aeba-0ab817a8b399")"
DEVICE_ROOT="/dev/$(lsblk -no pkname "${DEVICE_CHILD}")"
PART_NUM="${DEVICE_CHILD: -1}"

# Need resize
UNUSED=$(sfdisk -Fq "${DEVICE_ROOT}" | cut -d " " -f 3 | tail -1)
if [ -z "${UNUSED}" ] || [ "${UNUSED}" -le "16384" ]; then
    echo "[INFO] No resize of data partition needed"
    exit 0
fi

echo "[INFO] Update DVR partition ${PART_NUM}"
if sfdisk -dq "${DEVICE_ROOT}" | grep -q 'label: gpt'; then
    sgdisk -e "${DEVICE_ROOT}"
    sgdisk -d "${PART_NUM}" \
        -n "${PART_NUM}:0:0" \
        -c "${PART_NUM}:DVR" \
        -t "${PART_NUM}:EBD0A0A2-B9E5-4433-87C0-68B6B72699C7" \
        -u "${PART_NUM}:78eeef04-2a71-490b-aeba-0ab817a8b399" \
        "${DEVICE_ROOT}"
    sgdisk -v "${DEVICE_ROOT}"
else
    echo ", +" | sfdisk -N "${PART_NUM}" "${DEVICE_ROOT}" --force
    sfdisk -V "${DEVICE_ROOT}"
fi

partx -u "${DEVICE_ROOT}"

# Resize filesystem
echo "[INFO] Recreate DVR filesystem"
mkfs.exfat -s 131072 -n DVR "${DEVICE_CHILD}"
echo "[INFO] Finish DVR resizing"
