#!/bin/sh

mkdir -p /mnt/overlay/etc/

# Network
if [ ! -d /mnt/overlay/etc/NetworkManager/system-connections ]; then
    mkdir -p /mnt/overlay/etc/NetworkManager/system-connections
    cp -fp /etc/NetworkManager/system-connections/* /mnt/overlay/etc/NetworkManager/system-connections/
    chmod 600 /mnt/overlay/etc/NetworkManager/system-connections/*
fi

if [ ! -f /mnt/overlay/root/.bash_history ]; then
    cp -fp /root/.bash_history /mnt/overlay/root/.bash_history
fi

if [ ! -f /mnt/overlay/etc/hostname ]; then
    cp -fp /etc/hostname /mnt/overlay/etc/hostname
elif [ "$(cat /mnt/overlay/etc/hostname)" = "server" ]; then
    echo -n "dvr-server" > /mnt/overlay/etc/hostname
fi

if [ ! -f /mnt/overlay/etc/hosts ]; then
    cp -fp /etc/hosts /mnt/overlay/etc/hosts
fi

# Timezone
if [ -d /mnt/overlay/etc/timezone ]; then
    rm -rf /mnt/overlay/etc/timezone
fi
if [ ! -f /mnt/overlay/etc/timezone ]; then
    cp -fp /etc/timezone /mnt/overlay/etc/timezone
fi
ln -nsf "/usr/share/zoneinfo/$(cat /mnt/overlay/etc/timezone)" /mnt/overlay/etc/localtime

# TimeSync
if [ ! -f /mnt/overlay/etc/systemd/timesyncd.conf ]; then
    mkdir -p /mnt/overlay/etc/systemd
    cp -fp /etc/systemd/timesyncd.conf /mnt/overlay/etc/systemd/timesyncd.conf
fi

# Samba
if [ ! -d /mnt/overlay/var/lib/samba ]; then
    mkdir -p /mnt/overlay/var/lib/
    cp -af /var/lib/samba /mnt/overlay/var/lib/
fi

# systemd
if [ ! -d /mnt/overlay/etc/systemd/system.control ]; then
    mkdir -p /mnt/overlay/etc/systemd/system.control
fi